### ISSUE TITLE
Documentation: some reorg of Contributor's Guide pages

### ISSUE THREAD

**Issue by bugfolder** [backdrop-ops/docs.backdropcms.org#129]
I'd like to do a little bit of reorganization and cleanup of the [Contributor's Guide section](https://docs.backdropcms.org/documentation/contributors-guide). Describing my plans here for comments before I go start making changes.

Current organization of pages (per the menu block):

* Contributors Guide
    * How to use the core issue queue
    * Contribute to Backdrop
        * Contribute Backdrop Add-Ons
        * Contribute to Backdrop core
        * Contribute to Documentation
        * Become a maintainer
        * Adopt a project

Proposed changes:

* Flatten by one level so that all the ways to contribute are visible from the home page.
* Put "How to use the core issue queue" title into imperative form like the other titles: "Request Features/Report Problems" (which is actually the subheading on the page)
* Add a list of the other related issue queues to that page to help people make requests in the right places
* Eliminate "Contribute to Backdrop" as separate page (everything under "Contributor's Guide" is a way to contribute to Backdrop so that subdivision is not necessary). Move contents of that page into the (currently very short) "Contributor's Guide" page.
* Reorder so all core-related categories come first, then contrib-related categories.
* Fix capitalization of titles and corresponding menu entries

Proposed new hierarchy (what people will see in the menu block when they're on [https://docs.backdropcms.org](https://docs.backdropcms.org)):

* Contributors Guide
    * Request Features/Report Problems
    * Contribute to Backdrop Core
    * Contribute to Documentation
    * Contribute Backdrop Add-Ons
    * Become a Maintainer
    * Adopt a Project

**Comment by yorkshire-pudding** [comment]
@bugfolder - I think this can be closed

**Comment by bugfolder** [comment]
Agreed. It's evolved in a slightly different direction from the proposal, but I think the basic gist of this issue has been addressed.
