### ISSUE TITLE
Multiple fiedsets often time overlap with each other

### ISSUE THREAD

**Issue by alanmels** [backdrop-ops/docs.backdropcms.org#130]
Just go to https://docs.backdropcms.org/api/backdrop/core%21modules%21system%21system.api.php/function/hook_menu_link_alter/1 and see:

![Screenshot from 2021-04-18 20-41-08](https://user-images.githubusercontent.com/56604405/115174730-06338180-a087-11eb-8ef9-1ad852106586.png)

First click gives:

![Screenshot from 2021-04-18 20-44-02](https://user-images.githubusercontent.com/56604405/115174750-10558000-a087-11eb-8a52-f25f53626af7.png)

so you have to expand one more time.

**Comment by BWPanda** [comment]
Let me guess, you're using Firefox...? See https://github.com/backdrop/backdrop-issues/issues/4971 for the fix (we just need to update all our sites).

**Comment by alanmels** [comment]
Yep, I'm using the latest version of Firefox (87.0 (64-bit)). Anyway, if there is a fix it needs to go to https://docs.backdropcms.org as it is not nice to have malformatted documentation pages.

**Comment by jenlampton** [comment]
I just updated docs to 1.19.0 and it looks like this problem is now resolved, but could someone else check on an older version of FireFox to confirm?

**Comment by BWPanda** [comment]
Although I'm on the latest FF, I can confirm that I was seeing this problem previously on all Backdrop sites, but now it looks good on docs!
