### ISSUE TITLE
Documentation: Modules removed from core

### ISSUE THREAD

**Issue by novid** [backdrop-ops/docs.backdropcms.org#134]
There are some _tiny mistakes_ in [this documentation page](https://docs.backdropcms.org/documentation/upgrading-drupal-7-modules-that-have-been-removed-from-core) regarding to forum and poll modules. I needed **editorial access** to propose the changes but couldn't request for one because the registration workflow for **docs.backdropcms.org** is private. How can i request for editorial access?

**Comment by novid** [comment]
![Screenshot from 2021-05-30 15-59-10](https://user-images.githubusercontent.com/1545570/120102434-39762f80-c160-11eb-9b54-7ce84198fe3b.png)
![Screenshot from 2021-05-30 15-59-42](https://user-images.githubusercontent.com/1545570/120102436-3aa75c80-c160-11eb-9942-9b2b178c59af.png)

**Comment by bugfolder** [comment]
Hi @novid, thanks for pointing this out. I've made the changes on the documentation page.
