### ISSUE TITLE
[UX] Side menu covers part of table in Functions

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-ops/docs.backdropcms.org#152]
**Steps to reproduce**

1. Load https://docs.backdropcms.org/api/backdrop/functions on a desktop pc (my monitor has 1920 width)
2. View the screen

**Expected result**
Can see all the table

**Actual result**
Table is partially obscured by side menu
![nTsYZjip4A](https://user-images.githubusercontent.com/20357797/132059549-65a64134-50f6-4760-bc08-51a725a18361.gif)

**Comment by yorkshire-pudding** [comment]
https://docs.backdropcms.org/api/backdrop/classes is even worse
![AKLqAq3La6](https://user-images.githubusercontent.com/20357797/132059773-380b5710-b588-4ba8-8ace-eb70091ce7de.gif)

**Comment by jenlampton** [comment]
Maybe we should hide the sidebar, or move but below the content, on pages that we know are going to have wide content. I imagine this is a problem with the form API properties as well.

**Comment by bugfolder** [comment]
Sidebar doesn't show up on FAPI:

![fapi](https://user-images.githubusercontent.com/29214084/201430899-17aea654-773f-46c1-9739-997f03a91bc7.jpg)

**Comment by yorkshire-pudding** [comment]
I see on that page, it appears below the content, so that is probably the solution for these other pages.

**Comment by jenlampton** [comment]
I'd hate to overcomplicate all pages if we're only having this problem with
one. It seems like adding a single layout that uses the same template as
forms would be a simpler solution we could have in place right away.

**Comment by bugfolder** [comment]
There's at least two pages so afflicted. I suspect there's more. Certainly we could duplicate the FAPI layout, then give it visibility conditions for the pages that are affected and then add to the visibility conditions as we find more pages that have this issue.

Even the FAPI layout solution seems less than ideal, though. It's a huge, long page, and a person now has to scroll all the way to the bottom to discover the book menu. (It's better than covering up content, of course.)

I'd mentioned in the meeting that there were a lot of pages that would benefit from allowing the page content (or at least, tables) to expand to the full width. For example, most class pages, like [views_handler_filter_numeric](https://docs.backdropcms.org/api/backdrop/core%21modules%21views%21handlers%21views_handler_filter_numeric.inc/class/views_handler_filter_numeric/1) contain tables that are squashed from side to side to fit into the 2/3 of the fixed page width that they're allotted to. As you scroll down, that right 1/3 column is all whitespace, and its a little frustrating to have a wide-screen monitor with all that wasted whitespace next to the squashed table of members.

**Comment by yorkshire-pudding** [comment]
Perhaps we can replicate the FAPI layout for pages where content is obscured as a short term fix and then work towards a longer term improvement?

**Comment by jenlampton** [comment]
> and its a little frustrating to have a wide-screen monitor with all that wasted whitespace next to the squashed table of members.

It sounds like we also might benefit from a larger breakpoint in the theme. 

> Perhaps we can replicate the FAPI layout for pages where content is obscured as a short term fix and then work towards a longer term improvement?

I think this is a good compromise. Do what's easy first, then iterate and improve :) baby steps! 

> that there were a lot of pages that would benefit from allowing the page content (or at least, tables) to expand to the full width

I wonder if there's an existing JS library that would allow the tables to expand, when needed, as opposed to the sidebar. (I'm not sure that this is a better idea, just another one)

**Comment by bugfolder** [comment]
> Perhaps we can replicate the FAPI layout for pages where content is obscured as a short term fix...

Yes we can. However, since each page has its own distinct menu path (like `api/backdrop/functions`), each page will need its own custom layout whose path is that exact path.

I've set one up for the Functions page: https://docs.backdropcms.org/api/backdrop/functions. For other pages, we'd clone this layout and change its title and path to the new path. I've done this for the other page you mentioned, https://docs.backdropcms.org/api/backdrop/classes. Others that could probably benefit:

 * https://docs.backdropcms.org/api/backdrop/deprecated
 * https://docs.backdropcms.org/api/backdrop/files

If there are others, maybe folks could post the URLs as further comments in this issue.

(I note that this would be much more easily done by installing [Layout Wildcard module](https://backdropcms.org/project/layout_wildcard), or implementing a solution to the currently stalled [issue 1602](https://github.com/backdrop/backdrop-issues/issues/1602).)

**Comment by jenlampton** [comment]
@bugfolder I'd support adding Layout Wildcard to the docs site if you want to go that route. I've been thinking about that for some of the other b.org sites from time to time, as I think it would make ongoing maintenance easier, PLUS, it might give us some first-hand insight into how to un-stall 1602!

**Comment by bugfolder** [comment]
I've added Layout Wildcard module to docs.backdropcms.org, and have set a single layout named "api/backdrop/<various>" to apply to the .../classes, .../functions, .../deprecated and .../files pages.

There's still a need for some CSS lovin' on the TOC that's now at the bottom of the page, but at least all the content is visible. Leaving this issue open for future comment/ideas and CSS cleanup.

**Comment by yorkshire-pudding** [comment]
Thank you @bugfolder - that is much appreciated

**Comment by bugfolder** [comment]
Follow-up issue (possible alternatives) in https://github.com/backdrop-ops/docs.backdropcms.org/issues/215.

**Comment by yorkshire-pudding** [comment]
I think we can close this.  The original issue was fixed and all further work is in the follow up issue.
