### ISSUE TITLE
[UX] Support colored Github labels in documentation that talks about labels

### ISSUE THREAD

**Issue by bugfolder** [backdrop-ops/docs.backdropcms.org#163]
Github labels are an important part of the issue queue workflow and the documentation talks about which labels should be applied where in various places. Currently, though, labels are given as quoted text, as here (taken from https://docs.backdropcms.org/documentation/how-to-use-the-core-issue-queue):

![before](https://user-images.githubusercontent.com/29214084/146614533-b365c77f-6a10-479f-9666-df2dfc1f8e88.jpg)

With some added CSS, though, we can use GH labels inline in documentation pages that match their appearance in Github, which greatly improves clarity and readability. Like this:

![after](https://user-images.githubusercontent.com/29214084/146614627-a2e5fa28-2aba-4f89-8d04-477f9334f6db.jpg)

PR to follow.

**Comment by bugfolder** [comment]
PR is filed. The colored labels are generated FontAwesome-style, e.g., like this:
```
<span class="github-tag github-tag-pr-needs-code-review"></span>
```
for the "pr - needs code review" labels. The CSS contains definitions for all 30 of the labels in the Backdrop issue queue.

**Comment by docwilmot** [comment]
Thats cool.

**Comment by bugfolder** [comment]
Edited the PR to change the classes. The colored labels are generated FontAwesome-style, e.g., like this:
```
<span class="gh-label gh-label-pr-needs-code-review"></span>
```
for the "pr - needs code review" labels. Also added some CSS for hyperlinked labels, done like this:
```
<a class="gh-label-wrapper" href="..."><span class="gh-label gh-label-pr-needs-code-review"></span></a>
```
These pages in the Tugboat sandbox show off their usage:

* `documentation/how-to-use-the-core-issue-queue`
* `documentation/adding-labels-to-issues`
* `documentation/adding-milestones-to-issues`

**Comment by klonos** [comment]
@bugfolder if you feel like being fancy, https://api.github.com/repos/backdrop/backdrop-issues/labels gets you a JSON-formatted list of all labels in the issues repo. So you could explore ways automate this (in case these labels change name/colors in the future, or more are added etc.)

**Comment by bugfolder** [comment]
That's cool, thanks. Yes, I'll look into that for version 2.0.
