### ISSUE TITLE
Form API documentation: #field_prefix/#field_suffix inaccuracies

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/docs.backdropcms.org#170]
https://docs.backdropcms.org/form_api#field_prefix

https://docs.backdropcms.org/form_api#field_suffix

- I believe that in theory all fields are allowed to have `#field_prefix`/`#field_suffix`. We need to confirm that, but I have tested it on `'#type' => 'number'` and it works, yet number fields aren't listed in the "Used By" sections.
- Description for `#field_prefix` says:
  > Text or code that is placed directly in front of the textfield. This can be used to prefix a textfield with a constant string.

  for `#field_suffix`:
  > Text or code that is placed directly after a textfield. This can be used to add a unit to a textfield.
  
  These descriptions are assuming "textfield" - should be replaced with "the field".

**Comment by klonos** [comment]
Another bit of information that we should document is that, unlike `#prefix` and `#suffix`, the text added by the `#field_prefix`/`#field_suffix` properties before/after fields works properly with `#states`.

There's a d.org issue for this: https://www.drupal.org/project/drupal/issues/2838639 ...but while unsolved the above holds true and I think that it should be documented.

**Comment by bugfolder** [comment]
`field_prefix`/`field_suffix` are supported for anything that's processed by `theme_form_element()`.

**Comment by bugfolder** [comment]
I updated the "FAPI Check" report, that lists many (all?) known discrepancies between what's in code and what's in the FAPI (basically, this is a checklist of things that need fixing in FAPI). The examples of this issue are on the list.

https://docs.backdropcms.org/admin/reports/fapi-check

**Comment by bugfolder** [comment]
https://docs.backdropcms.org/form_api#field_prefix and https://docs.backdropcms.org/form_api#field_suffix have updated descriptions.

**Comment by bugfolder** [comment]
I think this has been addressed, so closing.
