### ISSUE TITLE
Broken link in https://docs.backdropcms.org/documentation/step-1-planning

### ISSUE THREAD

**Issue by argiepiano** [backdrop-ops/docs.backdropcms.org#178]
The link to [complete list of contributed modules that are no longer necessary](https://backdropcms.org/node/1683) shown in page: https://docs.backdropcms.org/documentation/step-1-planning leads to a Page not found

**Comment by bugfolder** [comment]
Thanks fixed! (There's two references to that list on that page. The first was correct, the second was bad. Now fixed.)
