### ISSUE TITLE
Another broken link in upgrade documentation

### ISSUE THREAD

**Issue by argiepiano** [backdrop-ops/docs.backdropcms.org#180]
This is in https://docs.backdropcms.org/documentation/step-1-planning

It shows the html code of the link rather than the link itself.

<img width="1150" alt="Screen Shot 2022-02-07 at 9 29 11 AM" src="https://user-images.githubusercontent.com/9938978/152830103-34ee470b-32e4-46a8-825a-0925b3a1be1e.png">

**Comment by bugfolder** [comment]
Thanks, fixed.
