### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by jromine** [backdrop-ops/docs.backdropcms.org#186]
The README.md file has a link to "issue tracker" and there is a typo in the URL "dcos.backdropcms.org".

**Comment by jromine** [comment]
I think yes, absolutely.

**Comment by bugfolder** [comment]
@jromine, could you clarify which README.md file you're referring to? 

On the docs site, there's [this page](https://docs.backdropcms.org/documentation/contrib-application-process) that refers to the [example README.md](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md), but that doesn't have the problems you describe in this issue.

**Comment by stpaultim** [comment]
@Ardent10 - You are welcome to help with any issue in any of our issue queues. However, I want to clarify a few things. 

1) This issue queue is specifically for our documentation website with documentation for Backdrop CMS. This site is built with Backdrop CMS, but this issue queue is not for Backdrop CMS in general, it's for a specific site related to Backdrop CMS. 

You can work on issues in this queue, but if you need to set up a test site (for more complicated issues), the process is a bit more complicated.

For this specific issue (once the typo is clarified), you could fork the repo, fix the type, and create a PR without the need to set up the site - which is pretty easy and something you could do.

2) Here is a link to the issue queue for the software that runs all Backdrop CMS sites - https://github.com/backdrop/backdrop-issues/issues

**Comment by jromine** [comment]
@bugfolder the file with the typo is https://github.com/backdrop-ops/docs.backdropcms.org/blob/main/README.md

**Comment by Ardent10** [comment]
> @bugfolder the file with the typo is https://github.com/backdrop-ops/docs.backdropcms.org/blob/main/README.md
> 
> The words "issue tracker" link to https://github.com/backdrop-ops/dcos.backdropcms.org/issues

Thankyou, I am working on this.

**Comment by jromine** [comment]
Thanks @Ardent10!

**Comment by Ardent10** [comment]
> Thanks @Ardent10!

Would love to contribute more : )

**Comment by stpaultim** [comment]
@Ardent10 - THANK YOU!
