### ISSUE TITLE
Searching for api function names is difficult

### ISSUE THREAD

**Issue by jromine** [backdrop-ops/docs.backdropcms.org#187]
Search on docs.backdropcms.org returns a variety of document types, including change notice, documentation page, and api page. By comparison Drupal has a separate API site at https://api.drupal.org which searches and returns only api pages.

On attempt to search for an api function containing the string "user_", the search box force-autocompletes this to "user_save", and shows a list of approximately 10 other matches. It is challenging to bypass this autocomplete and search for only "user_".

Upon search, a wide variety of pages are returned that are not relevant to my search for api pages. By comparison the Drupal API site does not force-autocomplete my search term, and returns an extensive list of api functions containing "user_" without unrelated materials.

As a developer, this makes my task in searching for api functions more challenging. I would like to be able to search for Backdrop api functions and see a list of all matching functions without other types of results.

One suggestion would be to add a document type selector for the search. 

![image](https://user-images.githubusercontent.com/350497/155905345-d3c51056-5705-4f4d-969c-4d9b8b373585.png)

Another option would be to have a separate api.backdropcms.org site like Drupal has.

**Comment by jromine** [comment]
I have located https://docs.backdropcms.org/api/backdrop/functions which helps me significantly with my api search needs.

**Comment by bugfolder** [comment]
Looks like that page addresses the issue, so closing.
