### ISSUE TITLE
Typo in change record page: Modules... added to core in Backdrop CMS

### ISSUE THREAD

**Issue by jromine** [backdrop-ops/docs.backdropcms.org#193]
The documentation page https://docs.backdropcms.org/change-records/modules-or-drupal-7-module-equivalent-features-added-to-core-in-backdrop-cms has some typos:

> Project browser | The Drupal 7 project_browser **_mdoule_** has been renamed  Project Installer. It also includes the **_instalation_** functionality  previously provided in Drupal 7, so that all project installation can be  safely disabled.

**Comment by klonos** [comment]
Thanks @jromine 🙏🏼  ...typos fixed. Care to have a second look and let me know if I got everything?

**Comment by jromine** [comment]
Also on same page:

> Token | The Drupal 7 token module has been integrated with the **Backrop** System module.

**Comment by klonos** [comment]
Huh, I fixed all those `Backrop ` instances + other typos in the first go (and then cleared caches too). Perhaps local browser cache on your end @jromine?

**Comment by jromine** [comment]
@klonos Sorry, I was still reading through the same page (no reload).

**Comment by klonos** [comment]
No worries @jromine ...I'm closing this issue then 🙂
