### ISSUE TITLE
FAPI: guidance on when to use <fieldset> vs <details>

### ISSUE THREAD

**Issue by bugfolder** [backdrop-ops/docs.backdropcms.org#197]
This comment  https://github.com/backdrop/backdrop-issues/issues/4556#issuecomment-1075077513 suggests that the FAPI docs could use some guidance on when to use a fieldset https://docs.backdropcms.org/form_api#fieldset versus using the new details element introduced in 1.20 https://docs.backdropcms.org/form_api#details. 

If folks could chime in here on what they think we should say (and we get something of a consensus), I'll merge that information into the FAPI description of both elements.

**Comment by indigoxela** [comment]
I belief, the [original issue](https://github.com/backdrop/backdrop-issues/issues/324) might help to clarify.

Drupal 8 completely switched from collapsible fieldsets to details elements, but that caused several problems with (backwards) compatibility. So in Backdrop we decided to *add* the new form element, but to not replace any existing ones (yet).

Fieldsets are still supposed to get widely used, but if *new collapsible* form items get added, it's recommended to use details instead wherever possible.
The reason behind that: collapsible fieldsets are supposed to be a "Drupalism" and details seem to be better re A11Y.

**Comment by bugfolder** [comment]
FAPI is updated:

https://docs.backdropcms.org/form_api/details

[/form_api/fieldset](https://docs.backdropcms.org/form_api/fieldset)

Closing the issue, but feel free to reopen and add corrections and/or further suggestions.
