### ISSUE TITLE
Github label names not displayed

### ISSUE THREAD

**Issue by kswan** [backdrop-ops/docs.backdropcms.org#198]
On this page, https://docs.backdropcms.org/documentation/how-to-use-the-core-issue-queue, the github label names are not displayed.

![image](https://user-images.githubusercontent.com/154391/159989942-7f819fb9-31d1-440c-bebc-a80155d20ea5.png)

They are not included in the HTML either.
![image](https://user-images.githubusercontent.com/154391/159990291-061f93f9-377a-43a5-89af-2329d819bad5.png)

I am not logged in if that makes a difference. I couldn't find a registration page and my backdropcms.org login didn't work on docs.backdropcms.org.

**Comment by bugfolder** [comment]
Thanks, fixed!

**Comment by bugfolder** [comment]
BTW @kswan, you need to register separately on backdropcms.org and docs.backdropcms.org to login to both (yes, single sign-on would be nice and is a goal for the future), but you don't need to be logged in to see the labels—the editor just needs to have remembered to update the page! Now done.
