### ISSUE TITLE
Documentation clarification on system_settings_form

### ISSUE THREAD

**Issue by ElusiveMind** [backdrop-ops/docs.backdropcms.org#199]
On the following page:

https://docs.backdropcms.org/api/backdrop/core%21modules%21system%21system.module/function/system_settings_form/1

There are references to 'default_setting' that should be 'default_value' in the example code.

Also - `settings_config` should be renamed `primary_config` in the example as well.

**Comment by bugfolder** [comment]
Hi @ElusiveMind, thanks for finding this!

The documentation of Backdrop functions (like this one) is in the docblock code for the function; in this case it's here:

https://github.com/backdrop/backdrop/blob/60add6a6be1f4e621f9667a28d992d733ce5440f/core/modules/system/system.module#L4389-L4465

So the way to update the description would be  to file a PR against backdrop core with the updated docblock information. Would you be willing to file this issue in the Backdrop core issue queue, https://github.com/backdrop/backdrop-issues/issues?

**Comment by bugfolder** [comment]
New issue created, closing this one.
