### ISSUE TITLE
Make "Related Github Issues:" in change records actually work like links

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/docs.backdropcms.org#20]
Currently they're plain text. 
See (last items in page) https://api.backdropcms.org/node/41660

**Comment by quicksketch** [comment]
Thanks, I think they were plain textfields because we didn't have link module at the time. Now we do. We might do a small data migration to switch these to link fields.

**Comment by BWPanda** [comment]
I tried just re-saving the node, but that didn't work, so yeah, need to convert the fields...

**Comment by klonos** [comment]
Not sure re how much work this'd be, but it seems like a low-hanging fruit and easy-win.

**Comment by BWPanda** [comment]
This should be fixed now. I added a new field, used a presave hook to copy URLs from the old field to the new one, bulk updated all published Change Records, then removed the presave hook and the old field.
