### ISSUE TITLE
Versioned extra directory - doesn't make sense

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-ops/docs.backdropcms.org#201]
On https://docs.backdropcms.org/documentation/versioned-extra-directory

It states the following:

```
config/
config/active
config/staging
config/versioned <-- track via Git
```

Then later says:

>**Deploying to prod** - moving upstream
local: Manually delete all files in the `versioned `directory.
local: Manually copy the all the files from the `active` directory into the `versioned` directory.
local: `git add` & `git commit` all files in `staging`.
local: `git push` to get all files into the Git repository.
production: `git pull` to pull all config changes onto the production server.
production: Manually copy the all the files from the `versioned` directory into the `staging` directory.
production: Run the config importer (via Backdrop UI).
When you `git pull` on the production server, the `staging` directory is unchanged. The config files must be manually copied from the `versioned` directory before they will be ready for import via the Backdrop UI.

And:

>**Sync local to prod** - moving downstream
production: Manually delete all files in the `versioned` directory.
production: Manually copy the all the files from the `active` directory into the `versioned` directory.
production: `git add` & `git commit` all files in `staging`.
production: `git push` to get all files into the Git repository.
local: `git pull` to pull all config changes onto the production server.
local: Manually copy the all the files from the `versioned` directory into the `staging` directory.
local: Run the config importer (via Backdrop UI).

We are copying files in `versioned` but then doing git with `staging`; that's not going to work

Or am I missing something?

**Comment by yorkshire-pudding** [comment]
What I think it should say is:

>**Deploying to prod** - moving upstream
local: Manually delete all files in the `versioned` directory.
local: Manually copy the all the files from the `active` directory into the `versioned` directory.
local: `git add` & `git commit` all files in ~~`staging`~~_**`versioned`**_.
local: `git push` to get all files into the Git repository.
production: `git pull` to pull all config changes onto the production server.
production: Manually copy the all the files from the `versioned` directory into the `staging` directory.
production: Run the config importer (via Backdrop UI).
When you `git pull` on the production server, the `staging` directory is unchanged. The config files must be manually copied from the `versioned` directory before they will be ready for import via the Backdrop UI.

And:

>**Sync local to prod** - moving downstream
production: Manually delete all files in the `versioned` directory.
production: Manually copy the all the files from the `active` directory into the `versioned` directory.
production: `git add` & `git commit` all files in ~~`staging`~~_**`versioned`**_.
production: `git push` to get all files into the Git repository.
local: `git pull` to pull all config changes onto the production server.
local: Manually copy the all the files from the `versioned` directory into the `staging` directory.
local: Run the config importer (via Backdrop UI).

**Comment by BWPanda** [comment]
Yep, looks like step 3 for both sections should say 'versioned' instead of 'staging'.

Also, I think step 5 from the second section should say "onto your local" instead of "onto the production server".

**Comment by yorkshire-pudding** [comment]
Correction completed.  Closing
