### ISSUE TITLE
Update the Form API documentation with the newly-introduced `#required_message` property

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/docs.backdropcms.org#209]
These were introduced with https://github.com/backdrop/backdrop-issues/issues/5348 (in Backdrop v1.23.0).

**Comment by bugfolder** [comment]
Should we introduce these now, noting that they are introduced with Backdrop v1.23.0, or wait until 1.23.0 is actually out?

**Comment by bugfolder** [comment]
If we add the line "Introduced in Backdrop 1.23", we could go ahead and add these. 

@klonos, @quicksketch, but looking at the code in the newly merged 1.x, I don't see any reference to `#required_value_missing`, and looking at [the patch file](https://patch-diff.githubusercontent.com/raw/backdrop/backdrop/pull/4054.patch), it looks like it was added and then removed. Was that an oversight?

**Comment by quicksketch** [comment]
Yeah in the end `#required_value_missing` was removed, see my comment (and @docwilmot's right before mine) at https://github.com/backdrop/backdrop-issues/issues/5348#issuecomment-1114051634

So there's only one new property to document.

**Comment by bugfolder** [comment]
['#required_message' is added to properties.](https://docs.backdropcms.org/form_api#required_message)

It will take a little while to get it connected to all the form elements (lots of individual node edits), so leaving this issue open for now.

**Comment by bugfolder** [comment]
There's still a fair amount to do, per this:

https://docs.backdropcms.org/admin/reports/fapi-check

But I think it needs some refining/checking; there's probably some false positives in there.

**Comment by bugfolder** [comment]
The refining could (should?) perhaps be moved to a follow-up issue.

**Comment by bugfolder** [comment]
https://docs.backdropcms.org/form_api#required_message is now connected to the various form elements, so closing this issue.
