### ISSUE TITLE
Session documentation mentions $_SESSION superglobal but this is not documented in Globals

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-ops/docs.backdropcms.org#212]
This pages (and more) mention the $_SESSION superglobal but it doesn't appear to be documented anywhere what this is about.

https://docs.backdropcms.org/api/backdrop/core%21includes%21session.inc/1

The most obvious place would seem to be under Globals

**Comment by bugfolder** [comment]
`$_SESSION` is a PHP predefined variable:

https://www.php.net/manual/en/reserved.variables.session.php

Maybe just add a link to the online PHP manual?

**Comment by yorkshire-pudding** [comment]
Thanks @bugfolder - I hadn't realised that.  Your suggestion makes sense.

**Comment by bugfolder** [comment]
Issue and PR filed.

**Comment by yorkshire-pudding** [comment]
This has been merged.
