### ISSUE TITLE
FAPI: Document that form also accepts #attached

### ISSUE THREAD

**Issue by kiamlaluno** [backdrop-ops/docs.backdropcms.org#218]
https://docs.backdropcms.org/form_api#special-elements does not report that `#attached` can be used with a form, despite code like the following one is correct.

```php
$form['#attached']['js'] = array(
  backdrop_get_path('module', 'ajax_example') . '/ajax_example.js',
);
```

With that code, `#attached` is added directly to `$form`, not a form element. `#attached` should show a checkmark also for *form*.

**Comment by bugfolder** [comment]
Thanks, @kiamlaluno! Fixed.
