### ISSUE TITLE
documentation for CKEditor 

### ISSUE THREAD

**Issue by leeksoup** [backdrop-ops/docs.backdropcms.org#226]
Suggested improvements to the CKEditor documentation at 

- https://backdropcms.org/project/ckeditor
- https://docs.backdropcms.org/documentation/text-formats-editors-filters

Please see forum post https://forum.backdropcms.org/forum/editing-nodes-makes-them-lose-formatting for motivation.

### Suggested additions to https://backdropcms.org/project/ckeditor
(heading)Caution when switching an existing site from no text editor to CKEditor

When Backdrop site uses no Text Editor for long text fields, the text is saved without any filtering. This is deliberate and based on the philosophy that Backdrop should preserve the original text input in the database. (See more in the documentation page on "[Text Formats, Editors & Filters](https://docs.backdropcms.org/documentation/text-formats-editors-filters).")

One common example is that even when "Convert line breaks into HTML (i.e. `<br>` and `<p>`)" is enabled, when a text format uses no text editor, the HTML tags will _not_ be saved in the database. Instead, the output filter will add them at display time.

However, when a site is set up with a Text Editor -- such as CKEditor -- enabled, that situation changes. CKEditor _does_ save the line breaks as HTML tags in the database.

One problematic consequence occurs when a site with many nodes saved without a text editor then enables CKEditor, and then someone goes to edit one of those previously-saved nodes. At this point, CKEditor will pull the old field data from the database, and will combine all the text without HTML line break tags into the same paragraph. An old node with only paragraphs in it will suddenly have only _one_ paragraph containing all the text.

There is currently no automated way to fix this. Some suggestions are posted at forum thread, "[Editing nodes makes them lose formatting](https://forum.backdropcms.org/forum/editing-nodes-makes-them-lose-formatting)"

Site administrators should be aware of this potential problem that could result from changing text format settings to include the use of a Text Editor and weigh the difficulty against the benefit of much easier node editing.

### Suggested additions to the Text entry editor section of https://docs.backdropcms.org/documentation/text-formats-editors-filters
Before the final paragraph of the section, add this new para:

However, before switching an existing site from using no text editor to using CKEditor, please see the "Caution when switching an existing site from no text editor to CKEditor" of the [CKEditor Backdrop documentation page](https://backdropcms.org/project/ckeditor).

**Comment by bugfolder** [comment]
Good suggestions. I've added these to those pages.
