### ISSUE TITLE
"PHP Coding Standards / Type Hinting" contains a wrong link

### ISSUE THREAD

**Issue by kiamlaluno** [backdrop-ops/docs.backdropcms.org#227]
[PHP Coding Standards / Type Hinting](https://docs.backdropcms.org/php-standards#type-hinting) contains the following sentence.

> Whenever possible, function and method parameters should specify their data types using [type hinting](http://php.net/manual/en/language.oop5.typehinting.php).

The link takes to a page that does not exist.

Instead of `http://php.net/manual/en/language.oop5.typehinting.php`, the link should be `https://www.php.net/manual/en/language.types.declarations.php`.

**Comment by bugfolder** [comment]
Thanks, fixed.
