### ISSUE TITLE
Some links given in Form API Reference are wrong

### ISSUE THREAD

**Issue by avpaderno** [backdrop-ops/docs.backdropcms.org#228]
On https://docs.backdropcms.org/form_api, there are sentences similar to the following one.

> ajax.js finds all the form elements on the page that have an [#ajax['callback']](https://docs.backdropcms.org/form_api#ajax_callback) or an [#ajax['path']](https://docs.backdropcms.org/form_api#ajax_path) set and adds an event handler for the [#ajax['event']](https://docs.backdropcms.org/form_api#ajax_event) set on that form element.

The links are not correct: For example, instead of `https://docs.backdropcms.org/form_api#ajax_callback`, it should be `https://docs.backdropcms.org/form_api#ajax['callback']`; instead of `https://docs.backdropcms.org/form_api#ajax_path`, it should be `https://docs.backdropcms.org/form_api#ajax['path']`.

I only noticed this in that page because I was looking for a documentation page that is referenced in the *Example for Developers* project to correct a `@see` link given there. The same issue could be present in other pages; if I find more of them, I will open a new issue.

**Comment by bugfolder** [comment]
I think I've fixed all the instances of this problem on that page. Feel free to reopen (or post a new issue) if you find others. Thanks, @avpaderno!
