### ISSUE TITLE
FAPI: missing checkbox and checkboxes in tables

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-ops/docs.backdropcms.org#239]
checkbox and checkboxes are documented in the FAPI docs BUT are MISSING in the initial tables of that page.

**Comment by bugfolder** [comment]
Presumably "that page" is https://docs.backdropcms.org/form_api.

Looks like this happened via a commit on 11/14 from @jenlampton that broke up the the FAPI tables on that page into smaller tables.

**Comment by bugfolder** [comment]
They're now added to the "Simple Elements" table.

**Comment by jenlampton** [comment]
Yes, Our previous top table was too wide for the page.

All the elements should have a new field for element type, and I did find
one element that wasn't classified yesterday too. If something appears
missing, it's possible it didn't have a value in the new filed.

Also if anyone has feelings about which table things should be in, feel
free to move them around!

**Comment by argiepiano** [comment]
Some other common ones are still missing from the tables. email, date, file...

**Comment by jenlampton** [comment]
I just built a view to show all elements with missing values, and updated the remaining ones. I think I got them all this time!

**Comment by robertgarrigos** [comment]
> Presumably "that page" is https://docs.backdropcms.org/form_api.
> 
sorry, yes. "that page" :-)

**Comment by bugfolder** [comment]
Looks like everything is now represented, but if anyone sees something missing, feel free to reopen this issue, or post a new one (if we add a new element or property), and I'll make the appropriate settings/connections.
