### ISSUE TITLE
FAPI: missing #href key in top tables

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-ops/docs.backdropcms.org#240]
`#href` key is missing from the top tables on the [FAPI docs page](https://docs.backdropcms.org/form_api) although there is the entry down the page at https://docs.backdropcms.org/form_api#href

**Comment by bugfolder** [comment]
Properties (like `#href`) are only shown in the top tables if they're included in one or more of the elements in that table (like `link`). I've added `#href` to the `link` property (where it belongs), and it now shows up as a row in the "Renderable Elements" table. Thanks, @robertgarrigos for pointing this out!

If there are other elements that can use that property, please note them in a follow-up comment to this issue and I'll add the property to those elements.
