### ISSUE TITLE
Incorrect reference on function hook_permission page

### ISSUE THREAD

**Issue by Graham-72** [backdrop-ops/docs.backdropcms.org#26]
![function hook_permission - backdrop cms api 2015-10-21 09-02-35](https://cloud.githubusercontent.com/assets/10559274/10631096/776b5bee-77d3-11e5-8311-7f11b9798b39.png)

I am trying to find an example of using the user_access() function. This page suggests that there is one in page_example.module, but it does not seem to be there,

**Comment by BWPanda** [comment]
@Graham-72 I think it means usage example of hook_permission() (e.g. https://api.backdropcms.org/api/backdrop/modules%21examples%21page_example%21page_example.module/function/page_example_permission/1 )

For examples of user_access(), see https://api.backdropcms.org/api/backdrop/core%21modules%21user%21user.module/function/user_access/1
