### ISSUE TITLE
Improve formatting of return values

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/docs.backdropcms.org#64]
In code:

```php
/**
 * Legacy wrapper to return the vocabulary object matching a vocabulary machine
 * name.
 *
 * @param $machine_name
 *   The vocabulary's machine name.
 *
 * @return TaxonomyVocabulary|false
 *   The taxonomy vocabulary, if it exists, FALSE otherwise. Results are
 *   statically cached.
 *
 * @see taxonomy_vocabulary_machine_name_load()
 */
function taxonomy_vocabulary_load($machine_name) {
  $vocabularies = taxonomy_vocabulary_load_multiple(array($machine_name));
  return reset($vocabularies);
}
```

[How this gets rendered](https://api.backdropcms.org/api/backdrop/core%21modules%21taxonomy%21taxonomy.module/function/taxonomy_vocabulary_load/1):

<img width="895" alt="Screen Shot 2019-06-20 at 4 59 07 am" src="https://user-images.githubusercontent.com/2423362/59792745-39d0e380-9318-11e9-9a5c-ea3010798654.png">

...there should be a line break there, or some other sort of separation between `TaxonomyVocabulary|false` and the rest of the sentence.

**Comment by klonos** [comment]
...perhaps bold the return value, and add a column after it (same as we do with params)? So that it is rendered like so instead:

<img width="924" alt="Screen Shot 2019-06-20 at 5 18 52 am" src="https://user-images.githubusercontent.com/2423362/59793852-ed3ad780-931a-11e9-9d6c-4ca3a8098f28.png">

**Comment by BWPanda** [comment]
Working on this...

**Comment by BWPanda** [comment]
[PR](https://github.com/backdrop-contrib/api/pull/3) made to API module that addresses this.

As mentioned in the PR, this does a weird thing with `@return` tags with no following data type indicator (bolding the first line of the documentation instead), but I see this as a [bug](https://github.com/backdrop/backdrop-issues/issues/3954) with the `@return` tags, not the regex here...

**Comment by jenlampton** [comment]
@BWPanda I applied your patch to the API module, but I'm not seeing a line-break on the `taxonomy_vocabulary_load()` page.

**Comment by BWPanda** [comment]
This is working (https://docs.backdropcms.org/api/backdrop/core%21modules%21taxonomy%21taxonomy.module/function/taxonomy_vocabulary_load/1), so we can close.
