### ISSUE TITLE
Trusted Host settings page needs editing

### ISSUE THREAD

**Issue by laryn** [backdrop-ops/docs.backdropcms.org#68]
https://api.backdropcms.org/documentation/trusted-host-settings

This was published early for the preview release. Just noting here there is a lot of editorial/unpolished text in the page yet, indicating links to change records are needed, and a few cases where "Drupal" is still used.

**Comment by BWPanda** [comment]
@laryn The change records links have been updated, and I can only see one reference to Drupal (which looks correct). Can you see if you think there's still changes needed here?

**Comment by laryn** [comment]
Would it be accurate to change "Backdrop 1.???" to "Backdrop 1.x"? The triple question marks look like draft content to me.

**Comment by BWPanda** [comment]
Ah, I don't think so. It looks like we're waiting for someone to test a specific version of Backdrop in those cases so we know what to recommend...

**Comment by jenlampton** [comment]
I think @klonos took care of this. Closing (please re-open if necessary!)
